version: '3.8'

services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: 'nmap'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    expose:
      - '3306'
    ports:
      - 127.0.0.1:3306:3306
    volumes:
      - ../build/database:/docker-entrypoint-initdb.d
      - nmap-db:/var/lib/mysql

volumes:
  nmap-db:
